### ISSUE TITLE
FSF-SPDX issues in other repositories

### ISSUE THREAD

**Issue by davidhedlund** [spdx/fsf-api#20]
These issues are referenced in https://git.savannah.gnu.org/cgit/directory.git/tree/subprojects/spdx/ISSUES
* https://github.com/spdx/spdx-spec/issues/93 (now https://github.com/spdx/LicenseListPublisher/issues/121)
* https://github.com/spdx/spdx-spec/issues/46

**Comment by CAM-Gerlach** [comment]
@davidhedlund Just out of curiosity, I'd be curious to know the purpose of that repo and how it intersects with this one? There didn't appear to be a high-level description of what its all actually for other than some technical discussion in the top-level readme, so I'm trying to piece together how it fits into the picture.

It seems like to distill down what is being requested here (I'm not a SPDX member myself like @goneall ), what is specifically being asked for on the code side is:

* Adding an affirmative false value for the `libre` tag per spdx/spdx-spec#93
* Adding a GNU GPLv3 compatibility value per spdx/spdx-spec#46

However, it would seem that at least from the perspective of this API, if a license is included here and lacks a `libre` tag, is this not necessarily equivalent to a `false` value `isFSFlibre` since the only licenses listed here are those the FSF evaluated? So would only the changes needed be on the SPDX side of things (i.e. other repos), or is something else needed here to support that?

**Comment by CAM-Gerlach** [comment]
@goneall Given both of these things are already present here on the FSF API side, is there something else we're missing here or should this issue go in one of the core SPDX repos consuming the API output, which are presumably where the requested changes would need to be made?

**Comment by goneall** [comment]
> Given both of these things are already present here on the FSF API side and the limitations seem to be in the core SPDX projects that consumes it, is there something else we're missing here that needs to be addressed in our codebase, as this issue here seems to imply?

Yes - here's an update or plan on the 2 issues:

- issue https://github.com/spdx/LicenseListPublisher/issues/121 If I understand the issue correctly, it has already been resolved - this was just a bug in the LicenseListPublisher.
- https://github.com/spdx/spdx-spec/issues/46 is an issue in the spec I plan on addressing during 3.0.

**Comment by goneall** [comment]
@davidhedlund Since these issues are being tracked in the other repos, can we close this?  I don't think there are any changes needed from the fsf-api to support either of the issues referenced.

**Comment by davidhedlund** [comment]
> @davidhedlund Since these issues are being tracked in the other repos, can we close this? I don't think there are any changes needed from the fsf-api to support either of the issues referenced.

True. I tracked them in https://directory.fsf.org/wiki/Free_Software_Directory:SPDX_Group#Issues
